version: '3.7'
services:
    mysql:
        image: mysql:latest
        container_name: mysql-container
        ports:
            - '3306:3306'
        volumes:
            - ./data:/var/lib/mysql
            - ./artifacts:/docker-entrypoint-initdb.d/schema.sql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=app
            - MYSQL_USER=app
            - MYSQL_PASSWORD=pass
